apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: local-nodeport
  namespace: lab28
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
