apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab28-platform
  namespace: argocd
spec:
  project: lab28
  source:
    repoURL: https://github.com/TimingTime/Day28-Track2-NguyenMinhPhuong-2A202601947.git
    targetRevision: cea46f07927ee13b509b8460bbcb827de4050ed9
    path: deploy/kubernetes/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: lab28
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
